# ext:REST Client ID > humao.rest-client
@host = http://localhost:9080


### Create Beach
POST {{host}}/beaches HTTP/1.1
content-type: application/json

{
    "lat": -33.792726,
    "lng": 151.289824,
    "name": "Manly",
    "position": "E"
}

### Get Forecast 
GET {{host}}/forecast HTTP/1.1


### Create user
POST {{host}}/users HTTP/1.1
content-type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com",
    "password": "1234"
}


### Test health check
GET {{host}}/system/health HTTP/1.1
