version: '3.9'

services:
  server-mongo:
    image: mongo

  server-express:
    image: node:20-alpine
    container_name: express-server
    ports:
      - "9080:3000"
    volumes:
      - ./:/app
    user: ${USER_ID:-node}
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    command: sh -c "yarn install && yarn start"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/system/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    secrets:
      - storm-glass-api-key
    environment:
      - STORM_GLASS_URL=https://api.stormglass.io/v2
      - DATABASE_SOURCE=mongodb://server-mongo:27017/surf-forecast
      - PORT=3000
      - NODE_ENV=dev
    depends_on:
      - server-mongo
    restart: on-failure
    stdin_open: true
    tty: true
    mem_limit: 2g
    mem_reservation: 1g
    cpus: "2.00"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "2.00"
        reservations:
          memory: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  storm-glass-api-key:
    file: ./secrets/storm-glass-api-key.txt
