name: Start Project Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-code:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      STORM_GLASS_TOKEN: 92f9abcd-d090-11ef-ab67-0242ac134573-94f9ac54-bb67-d010-11ef-0242ac130123
      STORM_GLASS_URL: https://api.stormglass.io/v2
      DATABASE_SOURCE: mongodb://localhost:27017/surf-forecast

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Check lint
        run: yarn lint:check

      - name: Check style
        run: yarn style:check

      - name: Run unit tests
        run: yarn test:unit

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 8.0

      - name: Run functional tests
        run: yarn test:functional
